name: 'Localization-Management'
author: 'Novaday'
description: 'This GitHub action is designed to simplify the localization process for Laravel, Vue, and Flutter applications.'
branding:
  icon: 'book-open'
  color: 'blue'
  
inputs:
  input_file:
    description: 'The Excell file'
    required: true
  generate_flutter:
    description: 'generate flutter arb file'
    required: false
    default: 'true'
  generate_laravel:
    description: 'generate laravel json format file'
    required: false
    default: 'true'    
  generate_vue:
    description: 'generate vue json format file'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: install  
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
      
    - run: python ${{ github.action_path }}/convert.py -input ${{ inputs.input_file }} -vue ${{ inputs.generate_vue }} -flutter ${{ inputs.generate_flutter }} -laravel ${{ inputs.generate_laravel }}
      shell: bash
